services:
  - type: web
    name: waste-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "python manage.py migrate && gunicorn wastemanagement.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wm
          property: connectionString
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        - "*"
